/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  Calculate calculate = new Calculate();

    public static void main(String[] args) {
      System.out.println(new App().getGreeting());

      
    }
}
